#' Description of the plot function for zeroSum s3 objects
#'
#' This function plots the CV-Error and its standard deviation
#' against the value of lambda of a zeroSumCVFit.
#'
#' @param fit fit object generated by zeroSumCVFit()
#'
#' @param main title of the generated plot
#'
#' @param gamma if a fusion CV was performed the only a cv plot for
#'    a selected gamma can be shown
#'
#' @param ... other arguments for the normal predict function if
#'              the fit is not a zeroSumCVFit object
#'
#' @return predicted values

#' @examples
#' set.seed(1)
#' x <- log2(exampleData$x+1)
#' y <- exampleData$y
#' fit <- zeroSumCVFit( x, y, alpha=1)
#' plot( fit, "test")
#'
#' @importFrom graphics abline arrows axis mtext title
#' @importFrom grDevices rgb
#'
#' @export
plot <- function( fit=NULL, main="", gamma=0, ... )
{
    if( any( class(fit) == "ZeroSumCVFit") )
    {
        ids <- which( fit$cv_stats[,1] == gamma )
        
        x <- log( fit$cv_stats[ids,2] )
        y   <- fit$cv_stats[ids,4]
        yER <- fit$cv_stats[ids,5]

        yMin <- min(y - yER)
        yMax <- max(y + yER)

        xMin <- min(x)
        col <-rgb(0.0, 0.2, 0.4)
        plot( x, y, pch=16, cex=0.5, col="black",
            xlab=NA, ylab=NA, ylim=c(yMin,yMax) )

        title( main=main, line=2.5)
        n     <- nrow( fit$cv_stats )
        steps <- floor(seq(1,n, length.out=15 ))

        axis( 3, line=0, at=x[steps],
            labels=fit$cv_stats[steps,6])

        mtext(side=1, text=expression("log("~lambda~")"), line=2.5)
        if( fit$type %in% zeroSumTypes[1:4,2] )
        {
            mtext(side=2, text="CV-MSE", line=2.5)
        } else
        {
            mtext(side=2, text="CV-LL", line=2.5)
        }
        arrows(x, y-yER, x, y+yER, code=3,angle=90,length=0.05,col=col,lwd=0.5)

        abline(v=x[fit$LambdaMinIndex], col="black", lty=3 )
        abline(v=x[fit$Lambda1SEIndex], col="black", lty=3 )        

    } else {
        UseMethod("plot")
    }
}
