#' Description of the predict function for zeroSum s3 objects
#'
#' This function uses zeroSumFit objects or zeroSumCVFit objects
#' to predict responses for a given data newx.
#'
#' @param fit fit object generated by zeroSumCVFit() or zeroSumFit()
#'
#' @param newx data matrix for which new responses should be predicted
#'             (rows==samples)
#'
#' @param s determines which lambda should be used for prediction if the 
#'          fit is a zeroSumCVFit object: lambda.min or lamda.1SE. If 
#'          the fit is a zeroSumFit this argument is ignored.
#'
#' @param ... other arguments for the normal predict function if the fit
#'            is not a zeroSum object
#'
#' @return predicted values
#'
#' @examples
#' set.seed(1)
#' data <- simulateData()
#' fit <- zeroSumCVFit( data$x, data$y, alpha=1)
#' predict(fit, data$x, s="lambda.min")
#'
#' @export
predict <- function( fit=NULL, newx=NULL, s="lambda.min", ... )
{
    if( any( class(fit)=="ZeroSumCVFit") || any( class(fit)=="ZeroSumFit") )  
    {   
        if( class(newx) != "matrix" | typeof(newx) != "double"  )  
        {
            stop("type of passed x is not a numeric matrix\n")
        }

        if( fit$type == "zeroSumElNet" || fit$type == "elNet" )
        {
            beta <- coef(fit, s=s)    
            predict <- newx %*% beta[-1] + beta[1]    
            return(predict)
            
        }

    } else 
    {
        UseMethod("predict")          
    }
}
